apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaap-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.2
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjavaapp-container
          image: maha4iac/myjavaaaplicatio:2
          ports:
            - containerPort: 8080
